coverage:
  badge:
    path: .github/octocov/badge.svg
  paths:
    - coverage.out
  exclude:
    - '**/*.pb.go'
    - '**/*.pb.json.go'
    - 'internal/generator/testpb/**'
  acceptable: 80%
comment:
  if: is_pull_request
  deletePrevious: true
summary:
