coverage:
  paths:
    - coverage.out
  exclude:
    - "**/*.pb.go"
    - "**/*.pb.json.go"
    - "internal/generator/testpb/**"
  acceptable: 80%
comment:
  if: is_pull_request
  deletePrevious: true
