// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: test.proto

package testpb

import (
	_ "github.com/protoc-contrib/protoc-gen-go-json/protoc_contrib/json"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Standalone enum at file scope.
type TopLevelKind int32

const (
	TopLevelKind_TOP_LEVEL_KIND_UNSPECIFIED TopLevelKind = 0
	TopLevelKind_TOP_LEVEL_KIND_A           TopLevelKind = 1
	TopLevelKind_TOP_LEVEL_KIND_B           TopLevelKind = 2
)

// Enum value maps for TopLevelKind.
var (
	TopLevelKind_name = map[int32]string{
		0: "TOP_LEVEL_KIND_UNSPECIFIED",
		1: "TOP_LEVEL_KIND_A",
		2: "TOP_LEVEL_KIND_B",
	}
	TopLevelKind_value = map[string]int32{
		"TOP_LEVEL_KIND_UNSPECIFIED": 0,
		"TOP_LEVEL_KIND_A":           1,
		"TOP_LEVEL_KIND_B":           2,
	}
)

func (x TopLevelKind) Enum() *TopLevelKind {
	p := new(TopLevelKind)
	*p = x
	return p
}

func (x TopLevelKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TopLevelKind) Descriptor() protoreflect.EnumDescriptor {
	return file_test_proto_enumTypes[0].Descriptor()
}

func (TopLevelKind) Type() protoreflect.EnumType {
	return &file_test_proto_enumTypes[0]
}

func (x TopLevelKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TopLevelKind.Descriptor instead.
func (TopLevelKind) EnumDescriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

// SkippedEnum opts out of JSON method generation.
type SkippedEnum int32

const (
	SkippedEnum_SKIPPED_ENUM_UNSPECIFIED SkippedEnum = 0
	SkippedEnum_SKIPPED_ENUM_A           SkippedEnum = 1
)

// Enum value maps for SkippedEnum.
var (
	SkippedEnum_name = map[int32]string{
		0: "SKIPPED_ENUM_UNSPECIFIED",
		1: "SKIPPED_ENUM_A",
	}
	SkippedEnum_value = map[string]int32{
		"SKIPPED_ENUM_UNSPECIFIED": 0,
		"SKIPPED_ENUM_A":           1,
	}
)

func (x SkippedEnum) Enum() *SkippedEnum {
	p := new(SkippedEnum)
	*p = x
	return p
}

func (x SkippedEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SkippedEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_test_proto_enumTypes[1].Descriptor()
}

func (SkippedEnum) Type() protoreflect.EnumType {
	return &file_test_proto_enumTypes[1]
}

func (x SkippedEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SkippedEnum.Descriptor instead.
func (SkippedEnum) EnumDescriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1}
}

type WithEnum_Kind int32

const (
	WithEnum_UNKNOWN WithEnum_Kind = 0
	WithEnum_ONE     WithEnum_Kind = 1
	WithEnum_TWO     WithEnum_Kind = 2
)

// Enum value maps for WithEnum_Kind.
var (
	WithEnum_Kind_name = map[int32]string{
		0: "UNKNOWN",
		1: "ONE",
		2: "TWO",
	}
	WithEnum_Kind_value = map[string]int32{
		"UNKNOWN": 0,
		"ONE":     1,
		"TWO":     2,
	}
)

func (x WithEnum_Kind) Enum() *WithEnum_Kind {
	p := new(WithEnum_Kind)
	*p = x
	return p
}

func (x WithEnum_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WithEnum_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_test_proto_enumTypes[2].Descriptor()
}

func (WithEnum_Kind) Type() protoreflect.EnumType {
	return &file_test_proto_enumTypes[2]
}

func (x WithEnum_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WithEnum_Kind.Descriptor instead.
func (WithEnum_Kind) EnumDescriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{2, 0}
}

// Basic covers scalar fields, oneofs, maps, and proto3 optional presence.
type Basic struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	A     string                 `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	// Types that are valid to be assigned to B:
	//
	//	*Basic_Int
	//	*Basic_Str
	B             isBasic_B         `protobuf_oneof:"b"`
	Map           map[string]string `protobuf:"bytes,4,rep,name=map,proto3" json:"map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	O             *string           `protobuf:"bytes,5,opt,name=o,proto3,oneof" json:"o,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Basic) Reset() {
	*x = Basic{}
	mi := &file_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Basic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Basic) ProtoMessage() {}

func (x *Basic) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Basic.ProtoReflect.Descriptor instead.
func (*Basic) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

func (x *Basic) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

func (x *Basic) GetB() isBasic_B {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *Basic) GetInt() int32 {
	if x != nil {
		if x, ok := x.B.(*Basic_Int); ok {
			return x.Int
		}
	}
	return 0
}

func (x *Basic) GetStr() string {
	if x != nil {
		if x, ok := x.B.(*Basic_Str); ok {
			return x.Str
		}
	}
	return ""
}

func (x *Basic) GetMap() map[string]string {
	if x != nil {
		return x.Map
	}
	return nil
}

func (x *Basic) GetO() string {
	if x != nil && x.O != nil {
		return *x.O
	}
	return ""
}

type isBasic_B interface {
	isBasic_B()
}

type Basic_Int struct {
	Int int32 `protobuf:"varint,2,opt,name=int,proto3,oneof"`
}

type Basic_Str struct {
	Str string `protobuf:"bytes,3,opt,name=str,proto3,oneof"`
}

func (*Basic_Int) isBasic_B() {}

func (*Basic_Str) isBasic_B() {}

// Nested exercises nested message emission.
type Nested struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nested) Reset() {
	*x = Nested{}
	mi := &file_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nested) ProtoMessage() {}

func (x *Nested) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nested.ProtoReflect.Descriptor instead.
func (*Nested) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1}
}

// WithEnum exercises enum rendering.
type WithEnum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          WithEnum_Kind          `protobuf:"varint,1,opt,name=kind,proto3,enum=tests.WithEnum_Kind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithEnum) Reset() {
	*x = WithEnum{}
	mi := &file_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithEnum) ProtoMessage() {}

func (x *WithEnum) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithEnum.ProtoReflect.Descriptor instead.
func (*WithEnum) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{2}
}

func (x *WithEnum) GetKind() WithEnum_Kind {
	if x != nil {
		return x.Kind
	}
	return WithEnum_UNKNOWN
}

// SkippedMessage opts out of JSON method generation — users can
// hand-roll their own MarshalJSON for this type.
type SkippedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkippedMessage) Reset() {
	*x = SkippedMessage{}
	mi := &file_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkippedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkippedMessage) ProtoMessage() {}

func (x *SkippedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkippedMessage.ProtoReflect.Descriptor instead.
func (*SkippedMessage) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{3}
}

func (x *SkippedMessage) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Nested_Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Basic         *Basic                 `protobuf:"bytes,1,opt,name=basic,proto3" json:"basic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nested_Message) Reset() {
	*x = Nested_Message{}
	mi := &file_test_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nested_Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nested_Message) ProtoMessage() {}

func (x *Nested_Message) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nested_Message.ProtoReflect.Descriptor instead.
func (*Nested_Message) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Nested_Message) GetBasic() *Basic {
	if x != nil {
		return x.Basic
	}
	return nil
}

var File_test_proto protoreflect.FileDescriptor

const file_test_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"test.proto\x12\x05tests\x1a!protoc_contrib/json/options.proto\"\xbc\x01\n" +
	"\x05Basic\x12\f\n" +
	"\x01a\x18\x01 \x01(\tR\x01a\x12\x12\n" +
	"\x03int\x18\x02 \x01(\x05H\x00R\x03int\x12\x12\n" +
	"\x03str\x18\x03 \x01(\tH\x00R\x03str\x12'\n" +
	"\x03map\x18\x04 \x03(\v2\x15.tests.Basic.MapEntryR\x03map\x12\x11\n" +
	"\x01o\x18\x05 \x01(\tH\x01R\x01o\x88\x01\x01\x1a6\n" +
	"\bMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x03\n" +
	"\x01bB\x04\n" +
	"\x02_o\"7\n" +
	"\x06Nested\x1a-\n" +
	"\aMessage\x12\"\n" +
	"\x05basic\x18\x01 \x01(\v2\f.tests.BasicR\x05basic\"[\n" +
	"\bWithEnum\x12(\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x14.tests.WithEnum.KindR\x04kind\"%\n" +
	"\x04Kind\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\a\n" +
	"\x03ONE\x10\x01\x12\a\n" +
	"\x03TWO\x10\x02\",\n" +
	"\x0eSkippedMessage\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value:\x04\xe0\xf3\x1a\x01*Z\n" +
	"\fTopLevelKind\x12\x1e\n" +
	"\x1aTOP_LEVEL_KIND_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10TOP_LEVEL_KIND_A\x10\x01\x12\x14\n" +
	"\x10TOP_LEVEL_KIND_B\x10\x02*E\n" +
	"\vSkippedEnum\x12\x1c\n" +
	"\x18SKIPPED_ENUM_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSKIPPED_ENUM_A\x10\x01\x1a\x04\xe0\xf3\x1a\x01BHZFgithub.com/protoc-contrib/protoc-gen-go-json/internal/generator/testpbb\x06proto3"

var (
	file_test_proto_rawDescOnce sync.Once
	file_test_proto_rawDescData []byte
)

func file_test_proto_rawDescGZIP() []byte {
	file_test_proto_rawDescOnce.Do(func() {
		file_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)))
	})
	return file_test_proto_rawDescData
}

var file_test_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_test_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_test_proto_goTypes = []any{
	(TopLevelKind)(0),      // 0: tests.TopLevelKind
	(SkippedEnum)(0),       // 1: tests.SkippedEnum
	(WithEnum_Kind)(0),     // 2: tests.WithEnum.Kind
	(*Basic)(nil),          // 3: tests.Basic
	(*Nested)(nil),         // 4: tests.Nested
	(*WithEnum)(nil),       // 5: tests.WithEnum
	(*SkippedMessage)(nil), // 6: tests.SkippedMessage
	nil,                    // 7: tests.Basic.MapEntry
	(*Nested_Message)(nil), // 8: tests.Nested.Message
}
var file_test_proto_depIdxs = []int32{
	7, // 0: tests.Basic.map:type_name -> tests.Basic.MapEntry
	2, // 1: tests.WithEnum.kind:type_name -> tests.WithEnum.Kind
	3, // 2: tests.Nested.Message.basic:type_name -> tests.Basic
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_test_proto_init() }
func file_test_proto_init() {
	if File_test_proto != nil {
		return
	}
	file_test_proto_msgTypes[0].OneofWrappers = []any{
		(*Basic_Int)(nil),
		(*Basic_Str)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_proto_goTypes,
		DependencyIndexes: file_test_proto_depIdxs,
		EnumInfos:         file_test_proto_enumTypes,
		MessageInfos:      file_test_proto_msgTypes,
	}.Build()
	File_test_proto = out.File
	file_test_proto_goTypes = nil
	file_test_proto_depIdxs = nil
}
