// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: protoc_contrib/json/options.proto

package json

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_protoc_contrib_json_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         55100,
		Name:          "protoc_contrib.json.skip",
		Tag:           "varint,55100,opt,name=skip",
		Filename:      "protoc_contrib/json/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         55100,
		Name:          "protoc_contrib.json.enum_skip",
		Tag:           "varint,55100,opt,name=enum_skip",
		Filename:      "protoc_contrib/json/options.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// When true, skip emitting MarshalJSON / UnmarshalJSON for this message.
	// Use this when a message needs a hand-written implementation.
	//
	// optional bool skip = 55100;
	E_Skip = &file_protoc_contrib_json_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.EnumOptions.
var (
	// When true, skip emitting MarshalJSON / UnmarshalJSON for this enum.
	//
	// optional bool enum_skip = 55100;
	E_EnumSkip = &file_protoc_contrib_json_options_proto_extTypes[1]
)

var File_protoc_contrib_json_options_proto protoreflect.FileDescriptor

const file_protoc_contrib_json_options_proto_rawDesc = "" +
	"\n" +
	"!protoc_contrib/json/options.proto\x12\x13protoc_contrib.json\x1a google/protobuf/descriptor.proto:5\n" +
	"\x04skip\x12\x1f.google.protobuf.MessageOptions\x18\xbc\xae\x03 \x01(\bR\x04skip:;\n" +
	"\tenum_skip\x12\x1c.google.protobuf.EnumOptions\x18\xbc\xae\x03 \x01(\bR\benumSkipBGZEgithub.com/protoc-contrib/protoc-gen-go-json/protoc_contrib/json;json"

var file_protoc_contrib_json_options_proto_goTypes = []any{
	(*descriptorpb.MessageOptions)(nil), // 0: google.protobuf.MessageOptions
	(*descriptorpb.EnumOptions)(nil),    // 1: google.protobuf.EnumOptions
}
var file_protoc_contrib_json_options_proto_depIdxs = []int32{
	0, // 0: protoc_contrib.json.skip:extendee -> google.protobuf.MessageOptions
	1, // 1: protoc_contrib.json.enum_skip:extendee -> google.protobuf.EnumOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protoc_contrib_json_options_proto_init() }
func file_protoc_contrib_json_options_proto_init() {
	if File_protoc_contrib_json_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protoc_contrib_json_options_proto_rawDesc), len(file_protoc_contrib_json_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_protoc_contrib_json_options_proto_goTypes,
		DependencyIndexes: file_protoc_contrib_json_options_proto_depIdxs,
		ExtensionInfos:    file_protoc_contrib_json_options_proto_extTypes,
	}.Build()
	File_protoc_contrib_json_options_proto = out.File
	file_protoc_contrib_json_options_proto_goTypes = nil
	file_protoc_contrib_json_options_proto_depIdxs = nil
}
