package generator_test

import (
	"strings"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protodesc"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/pluginpb"

	"github.com/protoc-contrib/protoc-gen-go-json/internal/generator"
	"github.com/protoc-contrib/protoc-gen-go-json/internal/generator/testpb"
)

// runGenerator builds a CodeGeneratorRequest for the given file descriptors,
// runs the plugin against it, and returns the emitted response.
func runGenerator(opts *generator.Options, files ...protoreflect.FileDescriptor) (*pluginpb.CodeGeneratorResponse, error) {
	req := &pluginpb.CodeGeneratorRequest{}
	seen := map[string]bool{}
	var walk func(fd protoreflect.FileDescriptor)
	walk = func(fd protoreflect.FileDescriptor) {
		if seen[fd.Path()] {
			return
		}
		seen[fd.Path()] = true
		imports := fd.Imports()
		for i := 0; i < imports.Len(); i++ {
			walk(imports.Get(i).FileDescriptor)
		}
		req.ProtoFile = append(req.ProtoFile, protodesc.ToFileDescriptorProto(fd))
	}
	for _, fd := range files {
		walk(fd)
		req.FileToGenerate = append(req.FileToGenerate, fd.Path())
	}
	plugin, err := protogen.Options{}.New(req)
	if err != nil {
		return nil, err
	}
	if err := generator.Generate(plugin, opts); err != nil {
		return nil, err
	}
	return plugin.Response(), nil
}

func emittedContent(resp *pluginpb.CodeGeneratorResponse) string {
	var sb strings.Builder
	for _, f := range resp.File {
		sb.WriteString(f.GetContent())
		sb.WriteString("\n")
	}
	return sb.String()
}

var _ = Describe("generator.Generate", func() {
	It("emits MarshalJSON and UnmarshalJSON for every message including nested ones", func() {
		resp, err := runGenerator(nil, testpb.File_internal_generator_testpb_test_proto)
		Expect(err).NotTo(HaveOccurred())
		Expect(resp.Error).To(BeNil())
		Expect(resp.File).To(HaveLen(1))

		out := emittedContent(resp)
		Expect(out).To(ContainSubstring("// Code generated by protoc-gen-go-json. DO NOT EDIT."))
		Expect(out).To(ContainSubstring("package testpb"))

		for _, name := range []string{"Basic", "Nested", "Nested_Message", "WithEnum"} {
			Expect(out).To(ContainSubstring("func (msg *" + name + ") MarshalJSON()"))
			Expect(out).To(ContainSubstring("func (msg *" + name + ") UnmarshalJSON("))
		}
	})

	It("skips synthetic map entry messages", func() {
		resp, err := runGenerator(nil, testpb.File_internal_generator_testpb_test_proto)
		Expect(err).NotTo(HaveOccurred())

		out := emittedContent(resp)
		Expect(out).NotTo(ContainSubstring("Basic_MapEntry"))
	})

	It("defaults every protojson flag to false when no options are set", func() {
		resp, err := runGenerator(nil, testpb.File_internal_generator_testpb_test_proto)
		Expect(err).NotTo(HaveOccurred())

		out := emittedContent(resp)
		Expect(out).To(ContainSubstring("UseEnumNumbers:  false"))
		Expect(out).To(ContainSubstring("EmitUnpopulated: false"))
		Expect(out).To(ContainSubstring("UseProtoNames:   false"))
		Expect(out).To(ContainSubstring("DiscardUnknown: false"))
	})

	It("propagates plugin options into the generated MarshalOptions", func() {
		opts := &generator.Options{
			EnumsAsInts:        true,
			EmitDefaults:       true,
			OrigName:           true,
			AllowUnknownFields: true,
		}
		resp, err := runGenerator(opts, testpb.File_internal_generator_testpb_test_proto)
		Expect(err).NotTo(HaveOccurred())

		out := emittedContent(resp)
		Expect(out).To(ContainSubstring("UseEnumNumbers:  true"))
		Expect(out).To(ContainSubstring("EmitUnpopulated: true"))
		Expect(out).To(ContainSubstring("UseProtoNames:   true"))
		Expect(out).To(ContainSubstring("DiscardUnknown: true"))
	})
})

var _ = Describe("generator.Options.Set", func() {
	It("parses each known flag as a boolean", func() {
		opts := &generator.Options{}
		Expect(opts.Set("enums_as_ints", "true")).To(Succeed())
		Expect(opts.Set("emit_defaults", "1")).To(Succeed())
		Expect(opts.Set("orig_name", "")).To(Succeed())
		Expect(opts.Set("allow_unknown", "false")).To(Succeed())

		Expect(opts.EnumsAsInts).To(BeTrue())
		Expect(opts.EmitDefaults).To(BeTrue())
		Expect(opts.OrigName).To(BeTrue())
		Expect(opts.AllowUnknownFields).To(BeFalse())
	})

	It("rejects unknown flags", func() {
		opts := &generator.Options{}
		Expect(opts.Set("nonsense", "true")).To(MatchError(ContainSubstring("unknown plugin option")))
	})

	It("rejects non-boolean values", func() {
		opts := &generator.Options{}
		Expect(opts.Set("emit_defaults", "maybe")).To(MatchError(ContainSubstring("invalid boolean value")))
	})
})
