// Package generator emits MarshalJSON and UnmarshalJSON methods for proto
// messages, delegating to google.golang.org/protobuf/encoding/protojson.
package generator

import (
	"google.golang.org/protobuf/compiler/protogen"
)

const (
	generatedFilenameSuffix = ".pb.json.go"
	protojsonImportPath     = protogen.GoImportPath("google.golang.org/protobuf/encoding/protojson")
)

// Generate walks every proto file scheduled for generation and emits a
// *.pb.json.go companion containing the MarshalJSON and UnmarshalJSON methods.
//
// The error return is currently always nil; it is reserved so future
// validation can report problems without breaking the signature.
func Generate(plugin *protogen.Plugin, opts *Options) error {
	if opts == nil {
		opts = &Options{}
	}
	for _, file := range plugin.Files {
		if !file.Generate {
			continue
		}
		generateFile(plugin, file, opts)
	}
	return nil
}

func generateFile(plugin *protogen.Plugin, file *protogen.File, opts *Options) {
	messages := collectMessages(file.Messages)
	if len(messages) == 0 {
		return
	}

	filename := file.GeneratedFilenamePrefix + generatedFilenameSuffix
	g := plugin.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-go-json. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	for _, msg := range messages {
		emitMessage(g, msg, opts)
	}
}

// collectMessages returns every message declared in the file, descending into
// nested messages and skipping synthetic map entries.
func collectMessages(msgs []*protogen.Message) []*protogen.Message {
	var out []*protogen.Message
	for _, m := range msgs {
		if m.Desc.IsMapEntry() {
			continue
		}
		out = append(out, m)
		out = append(out, collectMessages(m.Messages)...)
	}
	return out
}

func emitMessage(g *protogen.GeneratedFile, msg *protogen.Message, opts *Options) {
	marshal := protojsonImportPath.Ident("MarshalOptions")
	unmarshal := protojsonImportPath.Ident("UnmarshalOptions")

	g.P("// MarshalJSON implements json.Marshaler.")
	g.P("func (msg *", msg.GoIdent, ") MarshalJSON() ([]byte, error) {")
	g.P("return ", marshal, "{")
	g.P("UseEnumNumbers:  ", opts.EnumsAsInts, ",")
	g.P("EmitUnpopulated: ", opts.EmitDefaults, ",")
	g.P("UseProtoNames:   ", opts.OrigName, ",")
	g.P("}.Marshal(msg)")
	g.P("}")
	g.P()

	g.P("// UnmarshalJSON implements json.Unmarshaler.")
	g.P("func (msg *", msg.GoIdent, ") UnmarshalJSON(b []byte) error {")
	g.P("return ", unmarshal, "{")
	g.P("DiscardUnknown: ", opts.AllowUnknownFields, ",")
	g.P("}.Unmarshal(b, msg)")
	g.P("}")
	g.P()
}
